### ISSUE TITLE
安装Pillow失败，遇到报错The headers or library files could not be found for jpeg

### ISSUE THREAD

**Issue by elechuanwu** [chuanwu/WechatBot#27]
Pillow默认依赖libjpeg，在debian系上需要`sudo apt-get install libjpeg-dev`。
或者指定不需要jpeg，即`CFLAGS="--disable-jpeg" pip install pillow`。

**Comment by crazy-zhangcong** [comment]
centos6 安装的包名叫 libjpeg-turbo-devel
